### ISSUE TITLE
Gson Generic Support

### ISSUE THREAD

**Issue by michiwieland** [ADVisualizer/ADV-Lib#31]
Gson seems to be unable to serialize and deserialize complex generic objects. Understandably, they cannot infer the generic type at runtime (due to type erasure). Although this problem can be solved with gson-type-tokens, it is more tricky if we want to support any kind of types. (because we do not know which generic type argument is used by the student)

Due to this problem, the branch [Codestyle Branch](/ADVisualizer/ADV-Lib/tree/feature/codestyle) is not working properly. (v1.1 on Bintray)

Please see also:
- [Gson User Guide](https://github.com/google/gson/blob/master/UserGuide.md#TOC-Serializing-and-Deserializing-Generic-Types)
- [Gson Advanced Generics](https://futurestud.io/tutorials/gson-advanced-generics)
- [Gson: Deserialization of Generic Types](https://dzone.com/articles/deserialization-1)

**Comment by murieletrentini** [comment]
So wie ich das sehe haben wir zwei Möglichkeiten:
1. Generics weiterziehen in die Klassen (z.B. ModuleGroup<E,R> -> Typen der verwendeten Elements und Relations) damit wir die Type Tokens für Gson erstellen können [soetwas hatten wir bereits in einem früheren Stand des ADV...]
2. Eingrenzugn auf String -> würde für unsere bisherigen Anwendungsfälle wohl gehen. Zukünftig könnten aber keine beliebig komplexen Elemente verschickt werden.

**Comment by murieletrentini** [comment]
Wildcards should be supported in gson: https://github.com/google/gson/issues/39

**Comment by michiwieland** [comment]
@murieletrentini thx for merge. the updated version is now also available on master and maven central (fyi)
